package ru.geekbrains.marketAPI.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ru.geekbrains.marketAPI.db.model.Categories;
import ru.geekbrains.marketAPI.db.model.CategoriesExample;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    long countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int insert(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int insertSelective(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    Categories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int updateByExampleSelective(@Param("row") Categories row, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int updateByExample(@Param("row") Categories row, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int updateByPrimaryKeySelective(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Mon May 16 09:21:09 MSK 2022
     */
    int updateByPrimaryKey(Categories row);
}